version: "3.8"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=articlesDB
      - POSTGRES_USER=danwin
      - POSTGRES_PASSWORD=password
    networks:
      - db_go-network
  my-app:
    container_name: danwins-app
    image: docker-go-db-example:v3.0
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_started
    networks:
      - db_go-network

networks:
  db_go-network:
    driver: "bridge"
    external: true